### ISSUE TITLE
Make time based values on JwtClaimsData be temporal instead of longs

### ISSUE THREAD

**Issue by ckasabula** [nats-io/jwt.net#11]
### Proposed change

RE: The time based values on `JwtClaimsData`, i.e. `IssuedAt`/`Expires`/`NotBefore`. Could those be DateTimes? Or TimeSpans (offsets from now). I had to look at comments in the tests to see those values are unix timestamps (seconds).
`Expires = 1735689600, // 2025-01-01`
The older syntax `JwtUtils.IssueUserJwt` took a nullable `TimeSpan`.
It would be better if native c# temporal types were used.

### Use case

Use c# native, temporal types for `JwtClaimsData`.

**Comment by rickdotnet** [comment]
Are you wanting to interact with the model directly? Or, is there a method you're expecting to pass a DateTimeOffset to?

Would adding something like this to the model work? Not sure what rules are in place for the models, but spit-balling until @mtmk has a look.

```cs
[JsonIgnore]
public DateTimeOffset IssuedAtDateTime
{
    get => DateTimeOffset.FromUnixTimeSeconds(IssuedAt);
    set => IssuedAt = value.ToUnixTimeSeconds();
}

[JsonIgnore]
public DateTimeOffset ExpiresDateTime
{
    get => DateTimeOffset.FromUnixTimeSeconds(Expires);
    set => Expires = value.ToUnixTimeSeconds();
}

[JsonIgnore]
public DateTimeOffset NotBeforeDateTime
{
    get => DateTimeOffset.FromUnixTimeSeconds(NotBefore);
    set => NotBefore = value.ToUnixTimeSeconds();
}
```

**Comment by mtmk** [comment]
ah ok. didn't think of that, I was thinking we'd implement converters and change the types on the model to `DateTimeOffset` but his approach might be preferable if people want to be also able set the fields directly since that is the JWT standard at the end of the day.

**Comment by rickdotnet** [comment]
> I was thinking we'd implement converters and change the types on the model to `DateTimeOffset`

This is preferable, imo. It's cleaner and sets a better precedent if conversions become a common theme.

**Comment by ckasabula** [comment]
We are interacting directly with the model.
![image](https://github.com/user-attachments/assets/0b2f48b7-9f21-4c59-ba6b-2663bc9de902)

**Comment by rickdotnet** [comment]
Fix should be in soon. Extension methods can be your friend in that situation as well.

```
// datetimeoffset
uc.SetExpired(expires)

public static void SetExpired(this JwtClaimsData claimsData, DateTimeOffset expires)
    => claimsData.Expires = expires.ToUnixTimeSeconds();
```
