### ISSUE TITLE
Change type of data object for NatsGenericClaims

### ISSUE THREAD

**Issue by darkwatchuk** [nats-io/jwt.net#15]
### Proposed change

Currently NatsGenericClaims uses Dictionary<string, JsonObject> for its Data property. 

I think this should be changed to Dictionary<string, JsonNode>

### Use case

Some of the properties of the Data dictionary object need to be other types other than a JsonObject.

E.g. when calling "$SYS.REQ.CLAIMS.DELETE" we need a GenericClaims with a string array property called accounts.

Go example from https://github.com/nats-io/nats-server/blob/a07bde9fa7d499c7039f74cac9d11f4c046b9250/server/jetstream_jwt_test.go#L1005C2-L1010C28
```
generateRequest := func(accs []string, kp nkeys.KeyPair) []byte {
		t.Helper()
		opk, _ := kp.PublicKey()
		c := jwt.NewGenericClaims(opk)
		c.Data["accounts"] = accs
		cJwt, err := c.Encode(kp)
```

**Comment by mtmk** [comment]
resolved by #16
