### ISSUE TITLE
Standardize folder structure

### ISSUE THREAD

**Issue by rickdotnet** [nats-io/jwt.net#25]
### Proposed change

To maintain consistency with the [nats.net](https://github.com/nats-io/nats.net) repository, I propose we adopt the same folder structure for `jwt.net`. This will make it easier to expand with future docs, tools, and sandbox examples while keeping the repo clean and maintainable.

Proposed changes:

- Add `src` and `test` directories.
- Move existing files as necessary.
    - Adjust solution directories
    - Adjust CI/CD artifacts accordingly.

### Use case

This change makes it easier to build out features and maintain the project long-term.

### Contribution

_Indubitably_

cc: @mtmk

**Comment by mtmk** [comment]
makes sense to me 👍
